// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateMovie(ctx context.Context, arg CreateMovieParams) (sql.Result, error)
	CreateRating(ctx context.Context, arg CreateRatingParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteUser(ctx context.Context, username string) error
	GetMovie(ctx context.Context, id int) (Movie, error)
	GetRating(ctx context.Context, arg GetRatingParams) (Rating, error)
	GetRatings(ctx context.Context, username string) ([]Rating, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListRatings(ctx context.Context) ([]Rating, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateRating(ctx context.Context, arg UpdateRatingParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
